locals {
  # Anonymize the input or output if these types of data are detected
  # For example, if a US_SOCIAL_SECURITY_NUMBER is detected, it will be replaced with "US_SOCIAL_SECURITY_NUMBER"
  pii_anonymize_types = [
    # PII
    "US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER",
    "US_SOCIAL_SECURITY_NUMBER",
    "LICENSE_PLATE",
    "VEHICLE_IDENTIFICATION_NUMBER",
    "US_PASSPORT_NUMBER",

    # Financial
    "CREDIT_DEBIT_CARD_NUMBER",

    # Banking
    "SWIFT_CODE",
    "INTERNATIONAL_BANK_ACCOUNT_NUMBER",

    # Technical items
    "AWS_SECRET_KEY",
  ]

  # Block the input or output if these types of data are detected
  pii_block_types = []
}

resource "aws_bedrock_guardrail" "guardrail" {
  provider                  = aws.west2
  name                      = "VeraBotGuardrail"
  blocked_input_messaging   = "Your input has been blocked by the content filter. Please try again. If this is an error, discuss with the DevOps team."
  blocked_outputs_messaging = "The output generated by our system has been blocked by the content filter. Please try again. If this is an error, discuss with the DevOps team."
  description               = "Vera Guardrail"

  content_policy_config {
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "INSULTS"
    }
    filters_config {
      input_strength  = "LOW" # Medium strength blocking password reset questions
      output_strength = "MEDIUM"
      type            = "MISCONDUCT"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "SEXUAL"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "VIOLENCE"
    }
    filters_config {
      input_strength  = "NONE"
      output_strength = "NONE"
      type            = "PROMPT_ATTACK"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "HATE"
    }
  }

  sensitive_information_policy_config {
    dynamic "pii_entities_config" {
      for_each = local.pii_anonymize_types
      content {
        action = "ANONYMIZE"
        type   = pii_entities_config.value
      }
    }

    dynamic "pii_entities_config" {
      for_each = local.pii_block_types
      content {
        action = "BLOCK"
        type   = pii_entities_config.value
      }
    }
  }

  # topic_policy_config {
  #   topics_config {
  #     name = "company_investments"
  #     examples = [
  #       "When should I buy company stock?",
  #     ]
  #     type       = "DENY"
  #     definition = "Company investment advice refers to guidance of when to buy or sell company stock to generate profits. This is not allowed."
  #   }
  # }

}

resource "aws_bedrock_guardrail" "ue1_guardrail" {
  name                      = "Ue1${title(var.account_short_code)}VeraBotGuardrail"
  blocked_input_messaging   = "Your input has been blocked by the content filter. Please try again. If this is an error, discuss with the DevOps team."
  blocked_outputs_messaging = "The output generated by our system has been blocked by the content filter. Please try again. If this is an error, discuss with the DevOps team."
  description               = "Vera Guardrail"

  content_policy_config {
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "INSULTS"
    }
    filters_config {
      input_strength  = "LOW" # Medium strength blocking password reset questions
      output_strength = "MEDIUM"
      type            = "MISCONDUCT"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "SEXUAL"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "VIOLENCE"
    }
    filters_config {
      input_strength  = "NONE"
      output_strength = "NONE"
      type            = "PROMPT_ATTACK"
    }
    filters_config {
      input_strength  = "MEDIUM"
      output_strength = "MEDIUM"
      type            = "HATE"
    }
  }

  sensitive_information_policy_config {
    dynamic "pii_entities_config" {
      for_each = local.pii_anonymize_types
      content {
        action = "ANONYMIZE"
        type   = pii_entities_config.value
      }
    }

    dynamic "pii_entities_config" {
      for_each = local.pii_block_types
      content {
        action = "BLOCK"
        type   = pii_entities_config.value
      }
    }
  }

  # topic_policy_config {
  #   topics_config {
  #     name = "company_investments"
  #     examples = [
  #       "When should I buy company stock?",
  #     ]
  #     type       = "DENY"
  #     definition = "Company investment advice refers to guidance of when to buy or sell company stock to generate profits. This is not allowed."
  #   }
  # }

}